### ISSUE TITLE
Card not displaying correctly on iPad 

### ISSUE THREAD

**Issue by Johnh227** [martinville/solarsynkv2#17]
Hi. I use an I pad as a home display. For the past few days the solar synk card has not been displaying correctly and is squashed vertically. I have been into the layout in setting and tried to extend it down but it remains squashed with all the writing jumbled on top of each other. I have tried on safari and chrome. the same dashboard is displaying correctly on all other devices including iPhone. I have tried turning I pad of and on also. Do you know what it could be?

**Comment by martinville** [comment]
Hi John

If you are using the SlipX card then its due to an update that do not support older browsers anymore.

FYI this integration only generates data it does not render any charts or things. So I will close the issue.

**Comment by martinville** [comment]
closed
