### ISSUE TITLE
Loss of connection to SunSynk server causes Energy data issues

### ISSUE THREAD

**Issue by jeybee74** [martinville/solarsynkv2#20]
Hi,
The integration works great, but I often get wrong data in my Energy Chart, this is caused by some connection problems to the SS server I guess...?

![image](https://github.com/user-attachments/assets/6d3acc45-6b21-4a9f-96ed-134eaa850e2f)

![image](https://github.com/user-attachments/assets/ef855849-9064-459e-8718-23a162f2c19a)

Is there a quick fix so this, so I don't have to manually fix the Statistics for this data "all the time"
:)

**Comment by martinville** [comment]
Hi I'm afraid I don't have a solution for you. Quite often the SunSynk server becomes unavailable for the logger but is still available via API, The addon is still able to gather info but 0 values are served.

At the moment Its not possible for the addon to know when a value is "really" 0.

Sorry about that,

**Comment by martinville** [comment]
Hi Chris.

I see you requested some changes. I have not tested any of it, I hardly use
this integration i since moved over to Modbus over Rs232 using an ESP32.

I haven't tested any of the changes you requested, Can you confirm they
work ? Then I will just accept the changes.

**Comment by BlythMeister** [comment]
I'm running off my fork at the moment, it seems ok.  But maybe hold off just to be sure.  I'll comment on the PRs when I'm confident?

**Comment by martinville** [comment]
Ok great.

Thanks for the contribution.
