### ISSUE TITLE
Intermittent data

### ISSUE THREAD

**Issue by mdeakin99** [martinville/solarsynkv2#6]
I have noticed that the data feed is intermittent over the last two days,  this means that sometimes the battery discharge sometimes say 0w as well as the SOC (picture attached).

Have I configured something incorrectly or is this an issue on the SunSynk Cloud side.

![sunsynk](https://github.com/martinville/solarsynkv2/assets/54144679/570debce-a676-4095-89e2-a99aa3eae73a)

**Comment by mdeakin99** [comment]
Just realised this is probably related to https://github.com/martinville/solarsynkv2/issues/5 now I have looked through the error log.  Feel free to close if you want to :)

**Comment by martinville** [comment]
Yes, its related to Issue #5 , I made some changes to relieve most of the problems, please check #5 or the addons change log to see what was changed.

**Comment by martinville** [comment]
No longer an issue was addressed in an update
