### ISSUE TITLE
Mulitple inverters

### ISSUE THREAD

**Issue by ZAAJR** [martinville/solarsynkv2#9]
Hi Martin

In the "How it works" it says you support multiple inverters? I'd like to try pull data from 2 different inverters into my HA to monitor mine as well as my parents inverter. Can I do that?

Thanks

**Comment by martinville** [comment]
Hi it only supports multiple inverters on the same sunsynk account.

When you enter the inverter serial separate them with a semi colon I.E 123456789;689767898
